# Generated by Django 5.0.3 on 2024-04-23 07:22

import account.models
import django.db.models.deletion
import main.validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Supervisor'), (2, 'Lawyer'), (3, 'Customar')], null=True),
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[main.validator.validate_phone])),
                ('image', models.ImageField(upload_to=account.models.group_based_upload_to)),
                ('gender', models.CharField(choices=[('', 'Null'), ('ذكر', 'Male'), ('انثى', 'Female')], default='', max_length=22)),
                ('licence', models.FileField(upload_to='')),
                ('Qualification', models.FileField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
